name: 'Execução da Pipeline'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando dependências
        run: npm install &
      
      - name: Instalando dependências
        run: sleep 5

      - name: Executando os testes de API
        run: npm run tests:internal